apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-redis
spec:
  replicas: 1
  selector:
    app: k8s-redis
  template:
    metadata:
      labels:
        app: k8s-redis
    spec:
      containers:
      - name: redis
        image: redis
        port:
        - containerPort: 6379
