apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://172.19.0.5:8089"
  restauthenabled: "false"
  volumetype: "replicate:2"

