apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
#  annotations:
#    volume.alpha.kubernetes.io/storage-class: anything
  labels:
    app: minio-storage-claim
spec:
  storageClassName: local-gluster-heketi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

