kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: mynamespace
subjects:
- kind: ServiceAccount
  name: example-sa
  namespace: mynamepspace
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io
