scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
remote-write:
  - url: 'http://localhost:9201/write'
remote-read:
  - url: 'http://localhost:9201/read'

